# Generated by Django 3.2 on 2021-04-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True, verbose_name='Time when added')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(verbose_name='Current base MRP')),
                ('visibleToCostumer', models.BooleanField(verbose_name='should costumer see or not')),
                ('profitPercentage', models.FloatField(verbose_name='Profit ratio')),
                ('item_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
