# Generated by Django 3.2 on 2021-05-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': (('can_read_on_sunday', 'Can read only on sunday of the month'), ('can_manage_privilege', 'Can manage privileges'), ('can_read_privilege_detail', 'Can read privilege detail'))},
        ),
    ]
